[project]
name = "sales"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=40.1.0",
    "faker-commerce>=1.0.4",
    "pandas==2.2",
    "requests==2.32.3",
    "streamlit==1.52",
]
